// <auto-generated />
namespace PurchaseRequisition.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supervisor4172019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supervisor4172019));
        
        string IMigrationMetadata.Id
        {
            get { return "201904171702429_supervisor4172019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
